#!/bin/sh
echo "****************************************"
echo "*Please .. Restarting Enigma2          *"
echo "****************************************"
echo "*       Enjoy our plugin               *"
echo "****************************************"
echo "*   Please .. Restarting Enigma2       *"
echo "*    by Lululla                        *"
echo "*     all right reserved               *"
echo "*          no copy                     *"
echo "****************************************"
exit 0
